# Generated by Django 3.2.12 on 2023-04-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20230324_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Panier',
        ),
    ]
