# Generated by Django 3.2.12 on 2023-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20230324_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.TextField(),
        ),
    ]
